#pragma once

#ifndef DUCKDB_VERSION_H
#define DUCKDB_VERSION_H

#define DUCKDB_VERSION_MAJOR   0
#define DUCKDB_VERSION_MINOR   3
#define DUCKDB_VERSION_PATCH   3

#define DUCKDB_VERSION_NUMBER 0x000303
#define DUCKDB_VERSION_STRING  "0.3.3-devgf55b9a17f"

#define DUCKDB_DEV_ITERATION   844

#define DUCKDB_SOURCE "gf55b9a17f"

#endif