name: Python - Twine upload
on:
  workflow_call:
    inputs:
      override_git_describe:
        type: string
  workflow_dispatch:
    inputs:
      override_git_describe:
        type: string

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  OVERRIDE_GIT_DESCRIBE: ${{ inputs.override_git_describe }}

jobs:
   twine-upload:
      name: Twine upload
      runs-on: ubuntu-latest

      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}

      steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install
        shell: bash
        run: pip install twine

      - name: Download from staging bucket
        shell: bash
        run: |
          # decide target for staging
          if [ -z "$OVERRIDE_GIT_DESCRIBE" ]; then
            TARGET=$(git describe --tags --long)
          else
            TARGET="$OVERRIDE_GIT_DESCRIBE"
          fi
          mkdir to_be_uploaded
          aws s3 cp --recursive "s3://duckdb-staging/$TARGET/$GITHUB_REPOSITORY/twine_upload" to_be_uploaded --region us-east-2

      - name: Deploy
        env:
          TWINE_USERNAME: '__token__'
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
        shell: bash
        run: |
          if [[ "$GITHUB_REF" =~ ^(refs/heads/main|refs/tags/v.+)$ && "$GITHUB_REPOSITORY" = "duckdb/duckdb" ]] ; then
            twine upload --non-interactive --disable-progress-bar --skip-existing to_be_uploaded/*
          fi
